[2023-05-01T16:37:03.958+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawling_billboard.crawling scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-05-01T16:37:03.974+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawling_billboard.crawling scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-05-01T16:37:03.975+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-01T16:37:04.038+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): crawling> on 2023-04-23 00:00:00+00:00
[2023-05-01T16:37:04.054+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2023-05-01T16:37:04.061+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawling_billboard', 'crawling', 'scheduled__2023-04-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/crawling_billboard.py', '--cfg-path', '/tmp/tmpmancicdx']
[2023-05-01T16:37:04.068+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask crawling
[2023-05-01T16:37:04.180+0000] {task_command.py:410} INFO - Running <TaskInstance: crawling_billboard.crawling scheduled__2023-04-23T00:00:00+00:00 [running]> on host 03d33003d663
[2023-05-01T16:37:04.338+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawling_billboard' AIRFLOW_CTX_TASK_ID='crawling' AIRFLOW_CTX_EXECUTION_DATE='2023-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-23T00:00:00+00:00'
[2023-05-01T16:37:04.341+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawling_billboard.py", line 37, in crawling
    print("IT IS NOT SATURDAY", date)
UnboundLocalError: local variable 'date' referenced before assignment
[2023-05-01T16:37:04.356+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=crawling_billboard, task_id=crawling, execution_date=20230423T000000, start_date=20230501T163703, end_date=20230501T163704
[2023-05-01T16:37:04.379+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task crawling (local variable 'date' referenced before assignment; 168)
[2023-05-01T16:37:04.393+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-01T16:37:04.422+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
